### ISSUE TITLE
Autoscaling group config always shows alphabetically top entry

### ISSUE THREAD

**Issue by jpswinski** [SlideRuleEarth/sliderule-prov-sys#145]
When I go to reconfigure, it will always show the alphabetically first Asg_cfg even if the cluster is currently running with a different one.  This isn't a big deal, but I almost missed it because I went to change something else and only at the last second noticed that the Asg_cfg would also have changed if I hit update.

**Comment by cugarteblair** [comment]
fixed with v3.4.2
